server:
  port: 7777
accounts:
  datasource:
    url: jdbc:mysql://localhost:3306/docwiczenapi?serverTimezone=Europe/Warsaw&allowPublicKeyRetrieval=true&useSSL=False
    username: agnfal
    password: agnfal



